spring:
  application:
    name: polimarket-backend
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  datasource:
    url: jdbc:h2:mem:polimarketdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.polimarket: DEBUG

# Configuración JWT
jwt:
  secret: polimarket-secret-key-super-secure-for-jwt-tokens-2025
  expiration: 86400000 # 24 horas en milisegundos
